### ISSUE TITLE
Page can error out when hovering over an unknown item

### ISSUE THREAD

**Issue by nmss** [gw2efficiency/issues#817]
When I load https://gw2efficiency.com/account/overview
I got those error
```
script.js:5 Error: [$interpolate:interr] Can't interpolate: {{ characterValueTitle(character) }}
TypeError: Cannot read property 'value' of undefined
http://errors.angularjs.org/1.4.14/$interpolate/interr?p0=%7B%7BharacterValueTitle(character)%20%7D%7D&p1=TypeError%3A%20Cannot%20read%20property%20'value'%of%20undefined
    at https://gw2efficiency.com/scripts/script.js:2:17776
    at Function.$interpolateMinErr.interr (https://gw2efficiency.com/scripts/script.js:8:19336)
    at extend.exp (https://gw2efficiency.com/scripts/script.js:5:14538)
    at pre (https://gw2efficiency.com/scripts/script.js:4:21907)
    at invokeLinkFn (https://gw2efficiency.com/scripts/script.js:4:23552)
    at nodeLinkFn (https://gw2efficiency.com/scripts/script.js:4:8385)
    at compositeLinkFn (https://gw2efficiency.com/scripts/script.js:3:31121)
    at compositeLinkFn (https://gw2efficiency.com/scripts/script.js:3:31211)
    at https://gw2efficiency.com/scripts/script.js:3:29834
    at https://gw2efficiency.com/scripts/script.js:4:474
    at controllersBoundTransclude (https://gw2efficiency.com/scripts/script.js:4:6326)
    at https://gw2efficiency.com/scripts/script.js:10:25223
    at $watchCollectionAction (https://gw2efficiency.com/scripts/script.js:6:16722)
    at Scope.$digest (https://gw2efficiency.com/scripts/script.js:6:18306)
    at https://gw2efficiency.com/scripts/script.js:6:20119
    at completeOutstandingRequest (https://gw2efficiency.com/scripts/script.js:3:18486)
    at https://gw2efficiency.com/scripts/script.js:3:21557
    at wrapped (https://gw2efficiency.com/scripts/script.js:56:22532)
```

```
TypeError: Cannot read property 'value' of undefined
    at ChildScope.$scope.characterValueTitle (https://gw2efficiency.com/scripts/script.js:65:28163)
    at fn (eval at compile (https://gw2efficiency.com/scripts/script.js:9:157), <anonymous>:4:330)
    at https://gw2efficiency.com/scripts/script.js:6:2532
    at Scope.$digest (https://gw2efficiency.com/scripts/script.js:6:18015)
    at https://gw2efficiency.com/scripts/script.js:6:20119
    at completeOutstandingRequest (https://gw2efficiency.com/scripts/script.js:3:18486)
    at https://gw2efficiency.com/scripts/script.js:3:21557
    at wrapped (https://gw2efficiency.com/scripts/script.js:56:22532) undefined
```

let me know if you need more information

**Comment by queicherius** [comment]
These errors should not cause any issue with the page itself, what does not work for you?

**Comment by nmss** [comment]
You're right it's not the problem, I was too quick to submit this issue

Here is what is happening
- I search items on my account (in this case all ascended ring)
- hover them one by one, to look for the one with the stats I want
- at some point (seems random) the page end up redirected to another, that says there is an error while accessing the API
- then I need to go back to the search page and re-enter the search filters

It would be nice if I was not kicked out of the search page

**Comment by queicherius** [comment]
Uuuh. That should never happen ™️ 

Could you send me your API key and search terms that happens with to admin@gw2efficiency.com? Then I can investigate. Thanks!

**Comment by nmss** [comment]
Sure,
and if it can help please see this screenshot of the moment the error happens
![capture](https://user-images.githubusercontent.com/1228204/30226264-b1d74ccc-94d5-11e7-8d2f-7cd635a77916.PNG)

**Comment by queicherius** [comment]
The fix for this is now live. Thank you for your feedback. 😄
